Fix windows build
Summary:
We need to export symbols when building the library, but import them
when using the library.

Fixes issues like:
  .../moc_nicknamewidget.cpp(65): error C2491: 'ContactEditor::NicknameWidget::staticMetaObject': definition of dllimport static data member not allowed

Reviewers: sengels, mlaurent, dvratil

Reviewed By: dvratil

Subscribers: dvratil, kde-pim

Tags: #kde_pim

Differential Revision: https://phabricator.kde.org/D18523